language: rust
services: docker
sudo: required

matrix:
  include:
    - env: NAME="hmac MSRV"
      rust: 1.21.0
      script: cd hmac && cargo test --verbose
    - rust: 1.27.0
      script: cargo test --verbose --all
    - rust: stable
      script: cargo test --verbose --all
    - rust: nightly
      script: cargo test --verbose --all

    - env: TARGET=i686-unknown-linux-gnu
      rust: stable
    - env: TARGET=powerpc-unknown-linux-gnu
      rust: stable
    - env: TARGET=powerpc64-unknown-linux-gnu
      rust: stable
    # tests if crates truly can be built without std
    - env: TARGET=thumbv7em-none-eabi
      rust: nightly
      script: xargo build --verbose --target $TARGET
      install:
        - cargo install xargo || true
        - rustup target install armv7-unknown-linux-gnueabihf
        - rustup component add rust-src

install:
  - cargo install cross || true

script:
  - cross test --verbose --all --target $TARGET

cache: cargo
